Setup
carlos-ssh/booktify pull request #1
Opened 2021-12-08 00:48 UTC by carlos-ssh

- Get fresh React installation.
- Install Redux.
- Setting main files for this project.
- Add redux, material-ui and react-dom from npm.
- Remove files from public directory and remove a few lines of code on src/index.js related to removed components.
- Update README file.
- Update README add title and a description project's.
- Update README fix a list.
- Update README fix a list.
- Update README fix items.
- add linter setup for gh pr's.
- add scripts to linters.yml.
- add setup files for eslint and stylelint.
- add setup files stylelint.
- Delete README.old.md
- Add files for components and basic structure for each one.
- Import components and create routes.
- Add a form.
- Fixed linters error.

2021-12-08 01:56 UTC, Davidosky007 requested changes
## Hi @carlos-ssh 👋, 

Good job so far! 💪 
* Well written PR ✔️ 
* No linter errors ✔️ 
* Descriptive commit messages ✔️ 
* Professional looking readme file ✔️ 
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost-gif](https://user-images.githubusercontent.com/52497246/145134541-61199e9e-bce6-45c6-b875-90d00a120915.png)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-08 01:56 UTC, Davidosky007 commented on src/components/books/Books.js
> +);
* I suggest you make the books component a reusable one as currently it cant receive data as stated in the project [requirement ](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/project_init_project_wth_comps.md#:~:text=but%20it%20should%20be%20ready%20for%20the%20data) HINT 💭 you can create a new component that Takes the book data as a prop and renders the title and the author and also Has a button for removing books, the button wouldn't remove the books *yet*, as this is just a placeholder for now . it can now be imported here and rendered as many times by passing in different data ( author and title ) as props for each book

2021-12-08 01:56 UTC, Davidosky007 commented on src/components/categories/Categories.js
> +  </>
* Kindly display the proper content for each routes default page should not have the `Under construction` text displayed it should only be displayed in the categories route
![image](https://user-images.githubusercontent.com/52497246/145134010-bf7c9840-fc12-4517-8e9f-28c3c93a7e9e.png)

2021-12-08 04:18 UTC, ArthurGC requested changes
# Required Changes ♻️ :warning: 
Hi  @carlos-ssh 

Amazing job!
There are some issues that you still need to work on to go to the next project but you are almost there! 

![](https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif)

## Good Points :+1: :
You used proper GitHub Flow :heavy_check_mark:
Your linter checks are all passing :heavy_check_mark:
Your PR messages are descriptive :heavy_check_mark:
Your commit messages are meaningful :heavy_check_mark:

## Aspects to improve ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-08 04:18 UTC, ArthurGC commented on src/components/books/Books.js
> +);
- [ ] As the previous reviewer said, the `book` component should be reusable. The way to achieve this is using `props`.
If you want more information about it. This is a [good source.](https://www.w3schools.com/react/react_props.asp)

![react-props](https://user-images.githubusercontent.com/79876959/145146372-1cd75271-4ed0-4b92-8af5-dab2a05551e1.PNG)

As you see in the example, the Car component has a prop named brand. So if you send a different value to the brand prop, the Car component is going to show a different brand or content (`I am a Ford` or `I am a BMW`, etc.). The idea in the `Book` component is to have a title and author props so each time that you call the Book component with different props. It is going to render the same Book structure but with a different content that depends on its props. 😉 

It is necessary to do this because in the next milestones. You are going to receive a variable that stores all of your books. So your components should be ready for receiving data.

2021-12-11 19:13 UTC, D4nielJ approved these changes
## Hello @carlos-ssh, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

![](https://c.tenor.com/cojDoGCSxLkAAAAC/neil-patrick-harris-himym.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-11 19:17 UTC, merged